apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  selector:
    type: frontend
  ports:
    - name: http
      targetPort: 80
      port: 80
      nodePort: 30042
  type: LoadBalance
